import { Car } from '../car';

export const CARS: Car[] = [
        {
            "_id": "xsoEASzcB6nGGwA8D",
            "timestamp": "2015-12-21T23:51:17-08:00",
            "vehicle": "Corolla",
            "color": "White",
            "tagnum": "4545",
            "vin": "2678",
            "team": "TXM",
            "asm": "ASM",
            "status": "Prep",
            "notes": "First Note",
            "porter": "",
            "username": "austin.johnson.sd@gmail.com",
            "wash": "Yes",
            "company": "Austin's Company"
        },
        {
            "_id": "3k86kT7Tm8eFR2iYC",
            "timestamp": "2016-07-27T09:27:37-07:00",
            "vehicle": "Corolla",
            "color": "",
            "tagnum": "4988",
            "vin": "0404",
            "team": "TXM",
            "asm": "Jose",
            "status": "Prep",
            "notes": "NEED PARK VEHICLE INSIDE, WILL BE HERE A WHILE ",
            "porter": "",
            "username": "jvillegas@toyotaofelcajon.com",
            "wash": "Yes",
            "company": "Toyota of El Cajon"
        },
        {
            "_id": "nyk2XfCQKkTi4rxkc",
            "timestamp": "2016-07-27T09:28:07-07:00",
            "vehicle": "Corolla",
            "color": "",
            "tagnum": "4066",
            "vin": "984",
            "team": "TXM",
            "asm": "Jose",
            "status": "Prep",
            "notes": "NEED PARK VEHICLE INSIDE, WILL BE HERE A WHILE ",
            "porter": "",
            "username": "jvillegas@toyotaofelcajon.com",
            "wash": "Yes",
            "company": "Toyota of El Cajon"
        },
        {
            "_id": "w5NCcCLamYMiHBv7s",
            "timestamp": "2016-07-27T12:16:36-07:00",
            "vehicle": "Highlander",
            "color": "Burgandy",
            "tagnum": "5105",
            "vin": "4840",
            "team": "Silver",
            "asm": "Simo",
            "status": "Ready",
            "notes": "IN BOX",
            "porter": "",
            "username": "svukotich@toyotaofelcajon.com",
            "wash": "Already Washed",
            "company": "Toyota of El Cajon",
        },
        {
            "_id": "3Bt9QRzYqbnMqqRcG",
            "timestamp": "2016-07-27T12:57:03-07:00",
            "vehicle": "Venza",
            "color": "Brown",
            "tagnum": "5449",
            "vin": "985",
            "team": "Red",
            "asm": "Lance",
            "status": "Prep",
            "notes": "",
            "porter": "",
            "username": "ljones@toyotaofelcajon.com",
            "wash": "Yes",
            "company": "Toyota of El Cajon"
        },
        {
            "_id": "W4xBcv98hAWcJFKqW",
            "timestamp": "2016-07-27T13:18:05-07:00",
            "vehicle": "Corolla",
            "color": "Grey",
            "tagnum": "4042",
            "vin": "586",
            "team": "TXM",
            "asm": "Melissa",
            "status": "Prep",
            "notes": "",
            "porter": "",
            "username": "mmcmurtry@toyotaofelcajon.com",
            "wash": "Yes",
            "company": "Toyota of El Cajon"
        },
        {
            "_id": "gj5gGrdFDQbeKxTHr",
            "timestamp": "2016-07-27T14:04:44-07:00",
            "vehicle": "Camry",
            "color": "",
            "tagnum": "4044",
            "vin": "488",
            "team": "Gold",
            "asm": "Jose",
            "status": "Waiting",
            "notes": "",
            "porter": "",
            "username": "jvillegas@toyotaofelcajon.com",
            "wash": "Yes",
            "company": "Toyota of El Cajon"
        }
];